import { DataTable } from '@/components/ui/data-table/data-table';
import { sanitizeObject } from '@/components/ui/data-table/utils';
import { Title } from '@/components/ui/title';
import { columns } from '../column';
import { columns2 } from '../column2';
import { FilterItem } from '@/components/shared/filterItem';
import { Tabs } from '../../../components/shared/tabs';
import NotFound from '@/app/not-found';
import { statuses } from '../_layout';

const data2 = [
  {
    sl: 1,
    dateTime: '2024-03-26T09:00:00',
    name: 'John Doe',
    phoneNumber: '123-456-7890',
    emailAddress: 'john.doe@example.com',
    status: 'Pending',
    followUpDateTime: null,
    notes: ['First contact made.'],
  },
  {
    sl: 2,
    dateTime: '2024-03-27T10:15:00',
    name: 'Jane Smith',
    phoneNumber: '234-567-8901',
    emailAddress: 'jane.smith@example.com',
    status: 'Not Response',
    followUpDateTime: null,
    notes: ['Left voicemail.', 'Sent SMS reminder.'],
  },
  {
    sl: 3,
    dateTime: '2024-03-28T11:30:00',
    name: 'Emily Johnson',
    phoneNumber: '345-678-9012',
    emailAddress: 'emily.johnson@example.com',
    status: 'Not Qualified',
    followUpDateTime: null,
    notes: [],
  },
  {
    sl: 4,
    dateTime: '2024-03-29T12:45:00',
    name: 'William Brown',
    phoneNumber: '456-789-0123',
    emailAddress: 'william.brown@example.com',
    status: 'Potential',
    followUpDateTime: null,
    notes: ['Discussed product features.', 'Shared product brochure.'],
  },
  {
    sl: 5,
    dateTime: '2024-03-30T14:00:00',
    name: 'Sophia Miller',
    phoneNumber: '567-890-1234',
    emailAddress: 'sophia.miller@example.com',
    status: 'Hot',
    followUpDateTime: null,
    notes: ['Scheduled demo for next week.'],
  },
  {
    sl: 6,
    dateTime: '2024-03-31T15:15:00',
    name: 'Michael Wilson',
    phoneNumber: '678-901-2345',
    emailAddress: 'michael.wilson@example.com',
    status: 'Follow Up',
    followUpDateTime: '2024-04-07T15:15:00',
    notes: [],
  },
  {
    sl: 7,
    dateTime: '2024-04-01T16:30:00',
    name: 'Olivia Davis',
    phoneNumber: '789-012-3456',
    emailAddress: 'olivia.davis@example.com',
    status: 'Sold',
    followUpDateTime: null,
    notes: ['Closed the deal.', 'Sent thank you note.'],
  },
  {
    sl: 8,
    dateTime: '2024-04-02T17:45:00',
    name: 'Daniel Wilson',
    phoneNumber: '890-123-4567',
    emailAddress: 'daniel.wilson@example.com',
    status: 'Lost',
    followUpDateTime: null,
    notes: [],
  },
  {
    sl: 9,
    dateTime: '2024-04-03T18:00:00',
    name: 'Isabella Smith',
    phoneNumber: '901-234-5678',
    emailAddress: 'isabella.smith@example.com',
    status: 'Hot',
    followUpDateTime: null,
    notes: ['Met in person.', 'Requested more info via email.'],
  },
  {
    sl: 10,
    dateTime: '2024-04-04T09:00:00',
    name: 'Liam Johnson',
    phoneNumber: '012-345-6789',
    emailAddress: 'liam.johnson@example.com',
    status: 'Pending',
    followUpDateTime: null,
    notes: ['Initial outreach made.'],
  },
  {
    sl: 11,
    dateTime: '2024-04-05T10:15:00',
    name: 'Ava Williams',
    phoneNumber: '123-456-7890',
    emailAddress: 'ava.williams@example.com',
    status: 'Not Response',
    followUpDateTime: null,
    notes: ['Left voicemail.'],
  },
  {
    sl: 12,
    dateTime: '2024-04-06T11:30:00',
    name: 'Mason Brown',
    phoneNumber: '234-567-8901',
    emailAddress: 'mason.brown@example.com',
    status: 'Not Qualified',
    followUpDateTime: null,
    notes: [],
  },
  {
    sl: 13,
    dateTime: '2024-04-07T12:45:00',
    name: 'Luna Smith',
    phoneNumber: '345-678-9012',
    emailAddress: 'luna.smith@example.com',
    status: 'Potential',
    followUpDateTime: null,
    notes: ['Discussed pricing.'],
  },
  {
    sl: 14,
    dateTime: '2024-04-08T14:00:00',
    name: 'Ethan Davis',
    phoneNumber: '456-789-0123',
    emailAddress: 'ethan.davis@example.com',
    status: 'Hot',
    followUpDateTime: null,
    notes: ['Requested product demo.'],
  },
  {
    sl: 15,
    dateTime: '2024-04-09T15:15:00',
    name: 'Emma Wilson',
    phoneNumber: '567-890-1234',
    emailAddress: 'emma.wilson@example.com',
    status: 'Follow Up',
    followUpDateTime: '2024-04-16T15:15:00',
    notes: ['Scheduled follow-up call.'],
  },
  {
    sl: 16,
    dateTime: '2024-04-10T16:30:00',
    name: 'Oliver Johnson',
    phoneNumber: '678-901-2345',
    emailAddress: 'oliver.johnson@example.com',
    status: 'Sold',
    followUpDateTime: null,
    notes: ['Closed the deal.', 'Sent invoice.'],
  },
  {
    sl: 17,
    dateTime: '2024-04-11T17:45:00',
    name: 'Aria Smith',
    phoneNumber: '789-012-3456',
    emailAddress: 'aria.smith@example.com',
    status: 'Lost',
    followUpDateTime: null,
    notes: [],
  },
  {
    sl: 18,
    dateTime: '2024-04-12T18:00:00',
    name: 'Carter Davis',
    phoneNumber: '890-123-4567',
    emailAddress: 'carter.davis@example.com',
    status: 'Hot',
    followUpDateTime: null,
    notes: ['Sent follow-up email.'],
  },
  {
    sl: 19,
    dateTime: '2024-04-13T09:00:00',
    name: 'Charlotte Wilson',
    phoneNumber: '901-234-5678',
    emailAddress: 'charlotte.wilson@example.com',
    status: 'Pending',
    followUpDateTime: null,
    notes: ['Initial contact made.'],
  },
  {
    sl: 20,
    dateTime: '2024-04-14T10:15:00',
    name: 'Liam Williams',
    phoneNumber: '012-345-6789',
    emailAddress: 'liam.williams@example.com',
    status: 'Not Response',
    followUpDateTime: null,
    notes: ['Left voicemail.', 'Sent follow-up email.'],
  },
  {
    sl: 21,
    dateTime: '2024-04-15T11:30:00',
    name: 'Ava Brown',
    phoneNumber: '123-456-7890',
    emailAddress: 'ava.brown@example.com',
    status: 'Not Qualified',
    followUpDateTime: null,
    notes: [],
  },
  {
    sl: 22,
    dateTime: '2024-04-16T12:45:00',
    name: 'Mason Johnson',
    phoneNumber: '234-567-8901',
    emailAddress: 'mason.johnson@example.com',
    status: 'Potential',
    followUpDateTime: null,
    notes: ['Discussed features.'],
  },
  {
    sl: 23,
    dateTime: '2024-04-17T14:00:00',
    name: 'Luna Davis',
    phoneNumber: '345-678-9012',
    emailAddress: 'luna.davis@example.com',
    status: 'Hot',
    followUpDateTime: null,
    notes: ['Scheduled product demo.'],
  },
  {
    sl: 24,
    dateTime: '2024-04-18T15:15:00',
    name: 'Ethan Wilson',
    phoneNumber: '456-789-0123',
    emailAddress: 'ethan.wilson@example.com',
    status: 'Follow Up',
    followUpDateTime: '2024-04-25T15:15:00',
    notes: ['Sent follow-up email.'],
  },
  {
    sl: 25,
    dateTime: '2024-04-19T16:30:00',
    name: 'Emma Smith',
    phoneNumber: '567-890-1234',
    emailAddress: 'emma.smith@example.com',
    status: 'Sold',
    followUpDateTime: null,
    notes: ['Closed the deal.', 'Sent thank you note.'],
  },
  {
    sl: 26,
    dateTime: '2024-04-20T17:45:00',
    name: 'Oliver Brown',
    phoneNumber: '678-901-2345',
    emailAddress: 'oliver.brown@example.com',
    status: 'Lost',
    followUpDateTime: null,
    notes: [],
  },
  {
    sl: 27,
    dateTime: '2024-04-21T18:00:00',
    name: 'Aria Davis',
    phoneNumber: '789-012-3456',
    emailAddress: 'aria.davis@example.com',
    status: 'Hot',
    followUpDateTime: null,
    notes: ['Sent follow-up email.'],
  },
  {
    sl: 28,
    dateTime: '2024-04-22T09:00:00',
    name: 'Carter Wilson',
    phoneNumber: '890-123-4567',
    emailAddress: 'carter.wilson@example.com',
    status: 'Pending',
    followUpDateTime: null,
    notes: ['Initial contact made.'],
  },
  {
    sl: 29,
    dateTime: '2024-04-23T10:15:00',
    name: 'Charlotte Johnson',
    phoneNumber: '901-234-5678',
    emailAddress: 'charlotte.johnson@example.com',
    status: 'Not Response',
    followUpDateTime: null,
    notes: ['Left voicemail.'],
  },
  {
    sl: 30,
    dateTime: '2024-04-24T11:30:00',
    name: 'Liam Brown',
    phoneNumber: '012-345-6789',
    emailAddress: 'liam.brown@example.com',
    status: 'Not Qualified',
    followUpDateTime: null,
    notes: [],
  },
  {
    sl: 31,
    dateTime: '2024-04-25T12:45:00',
    name: 'Ava Johnson',
    phoneNumber: '123-456-7890',
    emailAddress: 'ava.johnson@example.com',
    status: 'Potential',
    followUpDateTime: null,
    notes: ['Discussed pricing.'],
  },
  {
    sl: 32,
    dateTime: '2024-04-26T14:00:00',
    name: 'Mason Davis',
    phoneNumber: '234-567-8901',
    emailAddress: 'mason.davis@example.com',
    status: 'Hot',
    followUpDateTime: null,
    notes: ['Requested product demo.'],
  },
  {
    sl: 33,
    dateTime: '2024-04-27T15:15:00',
    name: 'Luna Wilson',
    phoneNumber: '345-678-9012',
    emailAddress: 'luna.wilson@example.com',
    status: 'Follow Up',
    followUpDateTime: '2024-05-04T15:15:00',
    notes: ['Scheduled follow-up call.'],
  },
  {
    sl: 34,
    dateTime: '2024-04-28T16:30:00',
    name: 'Ethan Smith',
    phoneNumber: '456-789-0123',
    emailAddress: 'ethan.smith@example.com',
    status: 'Sold',
    followUpDateTime: null,
    notes: ['Closed the deal.', 'Sent invoice.'],
  },
  {
    sl: 35,
    dateTime: '2024-04-29T17:45:00',
    name: 'Emma Brown',
    phoneNumber: '567-890-1234',
    emailAddress: 'emma.brown@example.com',
    status: 'Lost',
    followUpDateTime: null,
    notes: [],
  },
  {
    sl: 36,
    dateTime: '2024-04-30T18:00:00',
    name: 'Oliver Johnson',
    phoneNumber: '678-901-2345',
    emailAddress: 'oliver.johnson@example.com',
    status: 'Hot',
    followUpDateTime: null,
    notes: ['Sent follow-up email.'],
  },
  {
    sl: 37,
    dateTime: '2024-05-01T09:00:00',
    name: 'Aria Davis',
    phoneNumber: '789-012-3456',
    emailAddress: 'aria.davis@example.com',
    status: 'Pending',
    followUpDateTime: null,
    notes: ['Initial contact made.'],
  },
  {
    sl: 38,
    dateTime: '2024-05-02T10:15:00',
    name: 'Carter Wilson',
    phoneNumber: '890-123-4567',
    emailAddress: 'carter.wilson@example.com',
    status: 'Not Response',
    followUpDateTime: null,
    notes: ['Left voicemail.'],
  },
  {
    sl: 39,
    dateTime: '2024-05-03T11:30:00',
    name: 'Charlotte Johnson',
    phoneNumber: '901-234-5678',
    emailAddress: 'charlotte.johnson@example.com',
    status: 'Not Qualified',
    followUpDateTime: null,
    notes: [],
  },
  {
    sl: 40,
    dateTime: '2024-05-04T12:45:00',
    name: 'Liam Brown',
    phoneNumber: '012-345-6789',
    emailAddress: 'liam.brown@example.com',
    status: 'Potential',
    followUpDateTime: null,
    notes: ['Discussed features.'],
  },
  {
    sl: 41,
    dateTime: '2024-05-05T14:00:00',
    name: 'Ava Johnson',
    phoneNumber: '123-456-7890',
    emailAddress: 'ava.johnson@example.com',
    status: 'Hot',
    followUpDateTime: null,
    notes: ['Scheduled product demo.'],
  },
  {
    sl: 42,
    dateTime: '2024-05-06T15:15:00',
    name: 'Mason Davis',
    phoneNumber: '234-567-8901',
    emailAddress: 'mason.davis@example.com',
    status: 'Follow Up',
    followUpDateTime: '2024-05-13T15:15:00',
    notes: ['Sent follow-up email.'],
  },
  {
    sl: 43,
    dateTime: '2024-05-07T16:30:00',
    name: 'Luna Wilson',
    phoneNumber: '345-678-9012',
    emailAddress: 'luna.wilson@example.com',
    status: 'Sold',
    followUpDateTime: null,
    notes: ['Closed the deal.', 'Sent thank you note.'],
  },
  {
    sl: 44,
    dateTime: '2024-05-08T17:45:00',
    name: 'Ethan Smith',
    phoneNumber: '456-789-0123',
    emailAddress: 'ethan.smith@example.com',
    status: 'Lost',
    followUpDateTime: null,
    notes: [],
  },
  {
    sl: 45,
    dateTime: '2024-05-09T18:00:00',
    name: 'Emma Brown',
    phoneNumber: '567-890-1234',
    emailAddress: 'emma.brown@example.com',
    status: 'Hot',
    followUpDateTime: null,
    notes: ['Sent follow-up email.'],
  },
  {
    sl: 46,
    dateTime: '2024-05-10T09:00:00',
    name: 'Oliver Johnson',
    phoneNumber: '678-901-2345',
    emailAddress: 'oliver.johnson@example.com',
    status: 'Pending',
    followUpDateTime: null,
    notes: ['Initial contact made.'],
  },
  {
    sl: 47,
    dateTime: '2024-05-11T10:15:00',
    name: 'Aria Davis',
    phoneNumber: '789-012-3456',
    emailAddress: 'aria.davis@example.com',
    status: 'Not Response',
    followUpDateTime: null,
    notes: ['Left voicemail.'],
  },
  {
    sl: 48,
    dateTime: '2024-05-12T11:30:00',
    name: 'Carter Wilson',
    phoneNumber: '890-123-4567',
    emailAddress: 'carter.wilson@example.com',
    status: 'Not Qualified',
    followUpDateTime: null,
    notes: [],
  },
  {
    sl: 49,
    dateTime: '2024-05-13T12:45:00',
    name: 'Charlotte Johnson',
    phoneNumber: '901-234-5678',
    emailAddress: 'charlotte.johnson@example.com',
    status: 'Potential',
    followUpDateTime: null,
    notes: ['Discussed pricing.'],
  },
  {
    sl: 50,
    dateTime: '2024-05-14T14:00:00',
    name: 'Liam Brown',
    phoneNumber: '012-345-6789',
    emailAddress: 'liam.brown@example.com',
    status: 'Hot',
    followUpDateTime: null,
    notes: ['Scheduled product demo.'],
  },
];

export default function Leads({ params }) {
  if (!statuses.some(status => status.value.toLowerCase().replace(' ', '-') === params.status)) return <NotFound />;
  const data = data2.filter(item => item.status.toLowerCase() === params.status.replace('-', ' '));
  return (
    <section>
      <Title className="max-md:text-center">Clients</Title>
      <Tabs params={params} baseURL="/leads" statuses={statuses} showAll />

      <div className="mt-4">
        <DataTable
          search="emailAddress"
          statuses={statuses}
          placeholder="Filter by Email Address"
          disableFilter
          customFilter={[
            {
              label: 'Follow Up Date',
              filter: FilterItem,
              props: {
                overrideLabel: true,
                checkbox: true,
              },
            },
          ]}
          data={sanitizeObject(data)}
          columns={params.status !== 'follow-up' ? columns2 : columns}
        ></DataTable>
      </div>
    </section>
  );
}
